export enum CommonReturns {
    INVALID_PASSWORD = "Invalid Password",
    USER_NOT_FOUND = "User not found",
    USER_ALREADY_EXISTS = "User already exists",
    USER_REGISTERED = "User registered successfully",
    SUCCESS = "Success",
    FAILED = "Failed",
    INVALID = "Invalid",
    EXPIRED = "Expired",
    USER_NOT_VERIFIED = "User not verified",
    USER_ALREADY_VERIFIED = "User already verified",
    MISSING_REQUIRED_FIELDS = "Missing required fields",
    INVALID_REQUEST = "Invalid request",
    SAME_PASSWORD = "Current password and new password are same",
}